select * from dbo.customerdata

Select *   into mycustomerdata from dbo.customerdata


select top  10 * from mycustomerdata


SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'mycustomerdata';


--Q1. What is the total revenue generated by male vs. female customers?

select gender,sum(purchase_amount) as total_Revenue
from mycustomerdata
group by gender
order by total_Revenue desc

--Q2. Which customers used a discount but still spent more than the average purchase amount? 


select customer_id, purchase_amount 
from mycustomerdata 
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from mycustomerdata)

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT TOP 5
    item_purchased,
    ROUND(AVG(TRY_CAST(review_rating AS FLOAT)), 2) AS Average_Product_Rating
FROM mycustomerdata
GROUP BY item_purchased
ORDER BY AVG(TRY_CAST(review_rating AS FLOAT)) DESC;


--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 


select shipping_type , avg(purchase_amount)
from mycustomerdata
where shipping_type = 'Standard' or shipping_type = 'Express'
group by shipping_type
order by avg(purchase_amount)

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.

select case when subscription_status = 'Yes' then 'Subscribed_Customer'
       else 'Non-Subscribed_Customer' end,
       COUNT(customer_id) AS total_customers,
       avg(purchase_amount) as Average, 
       sum(purchase_amount) as TotalRevenue
       from mycustomerdata
       group by case when subscription_status = 'Yes' then 'Subscribed_Customer'
       else 'Non-Subscribed_Customer' end

 
--Q6. Which 5 products have the highest percentage of purchases with discounts applied?


SELECT TOP 5
    item_purchased,
    ROUND(
        100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)
        / COUNT(*),
        2
    ) AS discount_rate
FROM mycustomerdata
GROUP BY item_purchased
ORDER BY discount_rate DESC;


--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 


    with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM mycustomerdata)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;


--Q8. What are the top 3 most purchased products within each category? 
with cte as (
select  category, item_purchased , count(*) as TotalCount, rank() over(partition by category order by count(*) desc) as rnk
from mycustomerdata
group by category , item_purchased
)
select rnk , category , item_purchased , TotalCount
from cte 
where rnk <=3


--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?


SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM mycustomerdata
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 

select age_group , sum(purchase_amount) as Revenue
from mycustomerdata
group by age_group
order by Revenue desc

